### ISSUE TITLE
This seems to be a bug

### ISSUE THREAD

**Issue by HppZ** [boostorg/property_tree#36]
parse xml file:

c++ code:

```c++
std::locale utf8Locale(std::locale(), new std::codecvt_utf8<wchar_t>());
std::wifstream f(*path);
f.imbue(utf8Locale);
wptree tree;
read_xml(f, tree);
```

xml file content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<data>
<content>你好&#128549;</content>
</data>
```

result is:
 "你好ð¥"
![image](https://user-images.githubusercontent.com/12285582/50680387-89f60b00-1042-11e9-91a5-b5fd27025caa.png)

other info:
boost property tree v 1.68.0
VS 2017 15.9.4 
Windows 10 17763.195

**Comment by HppZ** [comment]
@kaalus @Beman @jewillco

**Comment by HppZ** [comment]
@danieljames @Lastique @imikejackson

**Comment by Lastique** [comment]
It looks like rapidxml parser used in Boost.PropertyTree assumes that the output (parsed) encoding is UTF-8, regardless of the character type. Therefore the `&#128549;` constant gets decoded into 3 `wchar_t` elements instead of one or two depending on its encoding. The relevant code is here:

https://github.com/boostorg/property_tree/blob/29a7f0390b6904e9b7c447d1e6e44442bd0ab17b/include/boost/property_tree/detail/rapidxml.hpp#L1506-L1532

I believe, it should be specialized based on the resulting character type.

@HppZ You may try parsing XML into a narrow-character `ptree` and then converting it from UTF-8 to your `wchar_t` encoding.

PS: Mentioning everyone in the ticket won't get it solved sooner. It's actually quite rude, as now I have to spam people with my comment.

**Comment by HppZ** [comment]
I am really sorry and really thanks for your reply.

so there is a bug in rapidxml parser but how to report this bug to RapidXml since I don't see any contact info on the website [http://rapidxml.sourceforge.net/](http://rapidxml.sourceforge.net/).

**Comment by Lastique** [comment]
There's an obfuscated email of the author on that page. But since we maintain a local fork in Boost.PropertyTree, we might as well fix it locally.

**Comment by HppZ** [comment]
that is great. looking forward to your coming fix.
thanks!

**Comment by HppZ** [comment]
any plan to fix it? @Lastique

**Comment by Lastique** [comment]
I have no plans to proposing a fix currently.
